### ----------------Inicio sesion y recuperar contraseña----------
### registro
POST http://localhost:4000/api/administrador/registrar
content-type: application/json

{
  "cedula": "1726447888",
  "nombre": "Scarlett",
  "apellido": "Luna",
  "email": "sluna6360@gmail.com",
  "password": "Admin.123",
  "telefono": "998675191"
}

### Login
POST http://localhost:4000/api/administrador/login
content-type: application/json

{
  "email": "sluna6360@gmail.com",
  "password": "Admin.1234"
}

### recuperar contraseña administrador
POST http://localhost:4000/api/administrador/recuperar-clave
Content-Type: application/json

{
  "email": "sluna6360@gmail.com"
}
###nueva contraseña
PUT http://localhost:4000/api/administrador/nueva-clave/al3a3vrnq8h
Content-Type: application/json

{
  "password": "Admin.1234",
  "confirmarPassword": "Admin.1234"
}

### ------------------ FIN---------------------------------------


### --------------------------- Apartado guardias -----------------
### registro guardia
POST http://localhost:4000/api/administrador/registrar-guardia
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmNiMTc1NTQ1YzRkYWZhMTJmOWJhNSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzU5MTE3NDAsImV4cCI6MTczNTk5ODE0MH0.cCGt-p3krcD2XOlqHmbLDEcN3tb8rwL6nOnIhCL5JC0
content-type: application/json

{
  "nombre": "Amelia",
  "apellido": "Perez",
  "cedula": "1548955520",
  "email": "gifec83189@ckuer.com",
  "password": "Amelia.1234",
  "telefono": "0995777012",
  "estado": true
}

# {
#   "nombre": "Elsa",
#   "apellido": "Perez",
#   "cedula": "1548950420",
#   "email": "tixat81607@bawsny.com",
#   "password": "Manuel.123",
#   "telefono": "0995377002",
#   "estado": true
# }

# {
#   "nombre": "Lucia",
#   "apellido": "Perez",
#   "cedula": "1548951420",
#   "email": "kikesed300@kazvi.com",
#   "password": "Lucia.123",
#   "telefono": "0998370002",
#   "estado": true
# }

###listar guardia
GET  http://localhost:4000/api/administrador/listar-guardias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwMTgwNzgsImV4cCI6MTczNjEwNDQ3OH0.-mWP82topQKBERMmvxmbfl1SwsEJNSxvTk3mb5x8oSg

### actualizar perfil
PUT http://localhost:4000/api/administrador/actualizar-guardia/67641274d4f7e4451839f085
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWY2ZGZlOTE5YzU5ZjQyNjIxODU2YSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzQ2MTE1MDMsImV4cCI6MTczNDY5NzkwM30.qSM7SyVYM59BTGKulay2WUU6tHSubedr1Ol6fxcOPOw
content-type: application/json

{
  "nombre": "Elsa",
  "apellido": "Perez",
  "cedula": "1548950520",
  "email": "tixat81607@bawsny.com",
  "password": "Elsa.1234",
  "telefono": "0995377012",
  "estado": true
}

### cambiar estado 
PATCH http://localhost:4000/api/administrador/cambiar-estado-guardia/674e87202b4d752c4121e0d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTUxMzQ0NDUwNWIwNzhiMDljYzg3ZSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzM3MDMyNjAsImV4cCI6MTczMzc4OTY2MH0.C74JQOe8kFz-0OaM3soC51q7U51Q9vv5UF0F0OWWxJc
Content-Type: application/json

{
  "estado": false
}

### delete guardia
DELETE http://localhost:4000/api/administrador/eliminar-guardia/675636995754eec760b4a465
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTUxMzQ0NDUwNWIwNzhiMDljYzg3ZSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzM3MDMyNjAsImV4cCI6MTczMzc4OTY2MH0.C74JQOe8kFz-0OaM3soC51q7U51Q9vv5UF0F0OWWxJc

### -------------------------FIN Apartado guardias -----------------


###---------------------------- Apartado usuarios -----------------
### crear usuario
POST http://localhost:4000/api/administrador/registrar-usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmNiMTc1NTQ1YzRkYWZhMTJmOWJhNSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzU5MjU1ODksImV4cCI6MTczNjAxMTk4OX0.bngT6FUmuRGKc02uWcSIqG87psi61oWgCxVeWZiRSXo
Content-Type: application/json

{
  "nombre": "Stefany",
  "apellido": "Castellanos",
  "cedula": "1548951000",
  "email": "ejemplo@gmail.com",
  "password": "Stefany.123",
  "telefono": "0998374000",
  "placa_vehiculo": "aab-100",
  "rol": "Estudiante",
  "estado": true
}
### listar usuarios
GET http://localhost:4000/api/administrador/listar-usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwMTgwNzgsImV4cCI6MTczNjEwNDQ3OH0.-mWP82topQKBERMmvxmbfl1SwsEJNSxvTk3mb5x8oSg
Content-Type: application/json

### delete
DELETE http://localhost:4000/api/administrador/eliminar-usuario/676cd1e6e9bbc03a790c7bb6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwMTgwNzgsImV4cCI6MTczNjEwNDQ3OH0.-mWP82topQKBERMmvxmbfl1SwsEJNSxvTk3mb5x8oSg

### -------------------------FIN Apartado usuarios -----------------