### ----------------Inicio sesion y recuperar contraseña----------
### registro
POST http://localhost:4000/api/administrador/registrar
content-type: application/json

{
  "cedula": "1726447888",
  "nombre": "Scarlett",
  "apellido": "Luna",
  "email": "sluna6360@gmail.com",
  "password": "Admin.123",
  "telefono": "998675191"
}

### Login
POST http://localhost:4000/api/administrador/login
content-type: application/json

{
  "email": "sluna6360@gmail.com",
  "password": "Admin.1234"
}

### recuperar contraseña administrador
POST http://localhost:4000/api/administrador/recuperar-clave
Content-Type: application/json

{
  "email": "sluna6360@gmail.com"
}
###nueva contraseña
PUT http://localhost:4000/api/administrador/nueva-clave/al3a3vrnq8h
Content-Type: application/json

{
  "password": "Admin.1234",
  "confirmarPassword": "Admin.1234"
}

### ------------------ FIN---------------------------------------


### --------------------------- Apartado guardias -----------------
### registro guardia
POST http://localhost:4000/api/administrador/registrar-guardia
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYzMDY0OTMsImV4cCI6MTczNjM5Mjg5M30.jogkNr26p-9Sg31FZhbfUMYSX-IW3sx6k76Jlox-N7c
content-type: application/json

# {
#   "nombre": "ejemplo",
#   "apellido": "ejemplo",
#   "cedula": "1548955550",
#   "email": "bilib61354@evnft.com",
#   "password": "ejemplo.1234",
#   "telefono": "0995777002",
#   "estado": true
# }

{
  "nombre": "Elsa",
  "apellido": "Perez",
  "cedula": "1548950420",
  "email": "tixat81607@bawsny.com",
  "password": "Manuel.123",
  "telefono": "0995377002",
  "estado": true
}

# {
#   "nombre": "Lucia",
#   "apellido": "Perez",
#   "cedula": "1548951420",
#   "email": "kikesed300@kazvi.com",
#   "password": "Lucia.123",
#   "telefono": "0998370002",
#   "estado": true
# }

###listar guardia
GET  http://localhost:4000/api/administrador/listar-guardias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYzMDY0OTMsImV4cCI6MTczNjM5Mjg5M30.jogkNr26p-9Sg31FZhbfUMYSX-IW3sx6k76Jlox-N7c

### actualizar perfil
PUT http://localhost:4000/api/administrador/actualizar-guardia/677def866be1044b150db694
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYzMDY0OTMsImV4cCI6MTczNjM5Mjg5M30.jogkNr26p-9Sg31FZhbfUMYSX-IW3sx6k76Jlox-N7c
content-type: application/json

# {
#   "nombre": "Elsa",
#   "apellido": "Perez",
#   "cedula": "1548950520",
#   "email": "tixat81607@bawsny.com",
#   "telefono": "0995377012"
# }
{
  "telefono": "0995377112"
}

### cambiar estado 
PATCH http://localhost:4000/api/administrador/cambiar-estado-guardia/6779f8045093fe481880f76a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwNDg5NjcsImV4cCI6MTczNjEzNTM2N30.jLkfLku37nm0LAPsZ56rqf138S-v3Jcq-5V69SkVE2k
Content-Type: application/json

{
  "estado": true
}

### delete guardia
DELETE http://localhost:4000/api/administrador/eliminar-guardia/675636995754eec760b4a465
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTUxMzQ0NDUwNWIwNzhiMDljYzg3ZSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzM3MDMyNjAsImV4cCI6MTczMzc4OTY2MH0.C74JQOe8kFz-0OaM3soC51q7U51Q9vv5UF0F0OWWxJc

### -------------------------FIN Apartado guardias -----------------


###---------------------------- Apartado usuarios -----------------
### crear usuario
POST http://localhost:4000/api/administrador/registrar-usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzY1MTUxNjksImV4cCI6MTczNjYwMTU2OX0.Df8hNHHlfkW7188XoQvphrsb5Br9TariY7b9sSbk5aU
Content-Type: application/json

  {
  "nombre": "Vanessa",
  "apellido": "Guevara",
  "cedula": "1717849876",
  "email": "vanessa.guevarav@gmail.com",
  "telefono": 999669977,
  "password": "usuario.123",
  "placa":"PCF-267",
  "rol": "Docente",
  "estado":true
}
### listar usuarios
GET http://localhost:4000/api/administrador/listar-usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwMTgwNzgsImV4cCI6MTczNjEwNDQ3OH0.-mWP82topQKBERMmvxmbfl1SwsEJNSxvTk3mb5x8oSg
Content-Type: application/json

### delete
DELETE http://localhost:4000/api/administrador/eliminar-usuario/676cd1e6e9bbc03a790c7bb6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk4MTZmMzEzZThiMTZkYWFjMmY3NSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzYwMTgwNzgsImV4cCI6MTczNjEwNDQ3OH0.-mWP82topQKBERMmvxmbfl1SwsEJNSxvTk3mb5x8oSg

### -------------------------FIN Apartado usuarios -----------------