### -----------------------login----------------------
### login
POST http://localhost:3000/api/guardias/login
content-type: application/json

{
  "email": "gifec83189@ckuer.com",
  "password": "Amelia.123"
}


### recuperar contraseña
POST http://localhost:3000/api/guardias/recuperar-password
Content-Type: application/json

{
  "email": "gifec83189@ckuer.com"
}


### contraseña nueva
PUT http://localhost:3000/api/guardias/nueva-password/8nms6o98ei9
Content-Type: application/json

{
  "password": "Amelia.12345",
  "confirmarPassword": "Amelia.12345"
}
### ---------------------FIN login----------------------


### -----------------------perfil----------------------
### perfil guardia
GET http://localhost:3000/api/guardias/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MDQwNDgsImV4cCI6MTczMzc5MDQ0OH0.z5w9zMbPiL_Pgps4nqVsUBspkGOf2TKrNUqcdp1_Les

###actualizar contraseña
PUT http://localhost:3000/api/guardias/actualizar-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MDQwNDgsImV4cCI6MTczMzc5MDQ0OH0.z5w9zMbPiL_Pgps4nqVsUBspkGOf2TKrNUqcdp1_Les
Content-Type: application/json

  {
  "actualPassword": "Amelia.12345",
  "nuevoPassword": "Amelia.123"
}

### actualizar perfil guardia
PUT http://localhost:3000/api/guardias/67563960c579626f4a5fbf16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTMyNDAsImV4cCI6MTczMzc5OTY0MH0.Oc3k05fnT4mgi6qpgWhZe22M_QUC9jsqPtvOnhsEjDc
Content-Type: application/json

{
  "nombre": "Amelia",
  "apellido": "Lopez",
  "cedula": "1548955520",
  "email": "gifec83189@ckuer.com",
  "password": "Amelia.1234",
  "telefono": "0995577012",
  "estado": true
}

### ---------------------FIN perfil----------------------


### -----------------------usuarios----------------------
### Registrar usuario externo
POST http://localhost:3000/api/guardias/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3OTk4NjUsImV4cCI6MTczMzg4NjI2NX0.mHw4LAlyNq8tWoVcpG0Hq6AVKtd2Gr0AV-T5Ck_TkVw
Content-Type: application/json

{
  "nombre": "Stefany",
  "apellido": "Luna",
  "cedula": "1548951090",
  "email": "scarlettluna397@gmail.com",
  "password": "Luna.123",
  "telefono": "0998374400",
  "placa_vehiculo": "abc-110",
  "rol": "Estudiante",
  "estado": true
}

###listar usuario
GET  http://localhost:3000/api/guardias/listar-usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTM0MTMsImV4cCI6MTczMzc5OTgxM30.LeHquD1tshDQYBlCwd1mANRbTDdKAtSs26kWxb5VfHs
Content-Type: application/json

### cambiar estado usuario
PATCH  http://localhost:3000/api/guardias/cambiar-estado-usuario/67565e155d488118b0b84b2d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTM0MTMsImV4cCI6MTczMzc5OTgxM30.LeHquD1tshDQYBlCwd1mANRbTDdKAtSs26kWxb5VfHs
Content-Type: application/json

{
  "estado": false
}

### actualizar usuario externo
PUT http://localhost:3000/api/guardias/actualizar-usuarios/67565e155d488118b0b84b2d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTM0MTMsImV4cCI6MTczMzc5OTgxM30.LeHquD1tshDQYBlCwd1mANRbTDdKAtSs26kWxb5VfHs
Content-Type: application/json

{
  "nombre": "Estefany",
  "apellido": "Luna",
  "cedula": "1548951000",
  "email": "scarlettluna397@gmail.com",
  "password": "Luna.123",
  "telefono": "0998374400",
  "placa_vehiculo": "abb-110",
  "rol": "Estudiante",
  "estado": true
}

### ----------------------FIN usuarios----------------------

### -----------------------espacios----------------------
### parqueadero disponibles
GET http://localhost:3000/api/guardias/parqueaderos-disponibles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTM0MTMsImV4cCI6MTczMzc5OTgxM30.LeHquD1tshDQYBlCwd1mANRbTDdKAtSs26kWxb5VfHs