### -----------------------login----------------------
### login
POST http://localhost:4000/api/guardias/login
content-type: application/json

{
  "email": "tixat81607@bawsny.com",
  "password": "Guardia.456"
}


### recuperar contraseña
POST http://localhost:4000/api/guardias/recuperar-clave
Content-Type: application/json

{
  "email": "gifec83189@ckuer.com"
}

### contraseña nueva
PUT http://localhost:4000/api/guardias/nueva-clave/7z1xj4al0nr
Content-Type: application/json

{
  "password": "Amelia.12345",
  "confirmarPassword": "Amelia.12345"
}
### ---------------------FIN login----------------------


### -----------------------perfil----------------------
### perfil guardia
GET http://localhost:4000/api/guardias/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MDQwNDgsImV4cCI6MTczMzc5MDQ0OH0.z5w9zMbPiL_Pgps4nqVsUBspkGOf2TKrNUqcdp1_Les

###actualizar contraseña
PUT http://localhost:4000/api/guardias/actualizar-clave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzdlY2U3ZGRkZjQ1MzJjZDYzMjA5OSIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzYwMTg3OTcsImV4cCI6MTczNjEwNTE5N30.lR4VADp_VXfTBsiwz8ydTXoVLIA2d5iS7Vtp0DoNCE0
Content-Type: application/json

  {
  "actualPassword": "Amelia.12345",
  "nuevoPassword": "Amelia.123"
}

### actualizar perfil guardia
PUT http://localhost:4000/api/guardias/67563960c579626f4a5fbf16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTYzOTYwYzU3OTYyNmY0YTVmYmYxNiIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzM3MTMyNDAsImV4cCI6MTczMzc5OTY0MH0.Oc3k05fnT4mgi6qpgWhZe22M_QUC9jsqPtvOnhsEjDc
Content-Type: application/json

{
  "nombre": "Amelia",
  "apellido": "Lopez",
  "cedula": "1548955520",
  "email": "gifec83189@ckuer.com",
  "password": "Amelia.1234",
  "telefono": "0995577012",
  "estado": true
}

### ---------------------FIN perfil----------------------


### -----------------------usuarios----------------------
### Registrar usuario externo
POST http://localhost:4000/api/guardias/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2RlNzI4ZmIwNjg2ZGIwYTQ2NDllZCIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzY1MTc0NTQsImV4cCI6MTczNjYwMzg1NH0.5T9122xx1XCl5Ow4G52Ve3F9y5U4qr0C5AWXqay3Iuk
Content-Type: application/json

  {
  "nombre": "Vanessa",
  "apellido": "Guevara",
  "cedula": "1717849876",
  "email": "vanessa.guevarav@epn.edu.ec",
  "telefono": 999669977,
  "password": "usuario.123",
  "placa_vehiculo":"PCF-267",
  "rol": "Docente",
  "estado":true
}

###listar usuario
GET  http://localhost:4000/api/guardias/listar-usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2RlNzI4ZmIwNjg2ZGIwYTQ2NDllZCIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzYzMDQ0NjUsImV4cCI6MTczNjM5MDg2NX0.brXHuxrDU2PbVXh7E-f5kkA22mSpVVB2aSOxrpzropE
Content-Type: application/json

### cambiar estado usuario
PATCH  http://localhost:4000/api/guardias/cambiar-estado-usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2RlZjg2NmJlMTA0NGIxNTBkYjY5NCIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzY3Mjk0NDQsImV4cCI6MTczNjgxNTg0NH0.eHV95b7k27fiUg5q6-uCC6NyxHQV0zzMAzVanl6ljbQ
Content-Type: application/json

### actualizar usuario externo
PUT http://localhost:4000/api/guardias/actualizar-usuarios/677b6034c777b16afd0edff0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2RlNzI4ZmIwNjg2ZGIwYTQ2NDllZCIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzYzMDQ0NjUsImV4cCI6MTczNjM5MDg2NX0.brXHuxrDU2PbVXh7E-f5kkA22mSpVVB2aSOxrpzropE
Content-Type: application/json

{
  "nombre": "Estefany",
  "apellido": "Luna",
  "cedula": "1548951000",
  "email": "scarlettluna397@gmail.com",
  "telefono": "0998374400",
  "placa_vehiculo": "abb-120",
  "rol": "Docente"
}
###{
###  "rol": "Docente"
###}

### ----------------------FIN usuarios----------------------

### -----------------------Parqueadero----------------------
### reservar todo el parqueadero
PATCH http://localhost:4000/api/guardias/parqueaderos/6777ea78dddf4532cd632088
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzdlY2U3ZGRkZjQ1MzJjZDYzMjA5OSIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzU5Mzk3MDUsImV4cCI6MTczNjAyNjEwNX0.Pb8b-e8nR3HDs2AHWL_q_3-L8MXYLcxx3U2RBjy6Ccw
Content-Type: application/json

{
  "estado":true
}

### cambiar estado espacio
PATCH http://localhost:4000/api/guardias/parqueaderos-espacio/6777ea78dddf4532cd632088
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2RlZjg2NmJlMTA0NGIxNTBkYjY5NCIsInJvbCI6Imd1YXJkaWEiLCJpYXQiOjE3MzY3Mjk0NDQsImV4cCI6MTczNjgxNTg0NH0.eHV95b7k27fiUg5q6-uCC6NyxHQV0zzMAzVanl6ljbQ
Content-Type: application/json

{
  "estado": false,
  "numeroEspacio": "6"
}

