###parqeueadero
POST http://localhost:3000/api/parqueaderos/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2QwMTk1OWJiZmE0MmQ4ODZjZDYzOCIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3MzI4MDU3ODksImV4cCI6MTczMjg5MjE4OX0.wZp06wcV44zTAiUd6135yRQ_rhUkalU1uYh79DjEU10
Content-Type: application/json

{
  "nombre": "Parqueadero Esfot",
  "descripcion": "Parqueadero para vehículos",
  "planta": "A",
  "bloque": "A",
  "tipo": "Automovil",
  "espacios": 6
}