###Usuarios

###login
POST http://localhost:4000/api/usuarios/login
Content-Type: application/json

{
  "email": "scarlettluna397@gmail.com",
  "password": "Luna.12345"
}

# {
#   "email": "davidvela306@gmail.com",
#   "password": "David.123"
# }


### recuperar contraseña
POST http://localhost:4000/api/recuperar-clave
Content-Type: application/json

{
  "email": "scarlettluna397@gmail.com"
}

###nueva contraseña
PUT http://localhost:4000/api/nueva-clave/tr6dix430z9
Content-Type: application/json

{
  "password": "Luna.12345",
  "confirmarPassword": "Luna.12345"
}

###perfil
GET http://localhost:4000/api/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTdhZmYzNGM3ZGJjODJhOTllNjQ3MyIsInJvbCI6InVzdWFyaW8iLCJpYXQiOjE3MzM4MDAwNTksImV4cCI6MTczMzg4NjQ1OX0.QJU98ZXF1X2JLZQxwrWqX4q3l0lGzqSKyv3bQSHFUFg


###actualizar contraseña
PUT http://localhost:4000/api/usuarios/actualizar-clave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk3ODdhNzYzZDY2OWIxM2Q3YWVmNiIsInJvbCI6InVzdWFyaW8iLCJpYXQiOjE3MzYwMTkwNTQsImV4cCI6MTczNjEwNTQ1NH0.rsfuBHvf0cTax9fdB0t7-_0Wb44z3w7ibGeKz3Xjpw8
Content-Type: application/json

{
  "actualPassword": "Luna.12345",
  "nuevoPassword": "Luna.123"
}

### actualizar usuario 
PUT http://localhost:4000/api/usuarios/6757aff34c7dbc82a99e6473
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTdhZmYzNGM3ZGJjODJhOTllNjQ3MyIsInJvbCI6InVzdWFyaW8iLCJpYXQiOjE3MzM4MDAwNTksImV4cCI6MTczMzg4NjQ1OX0.QJU98ZXF1X2JLZQxwrWqX4q3l0lGzqSKyv3bQSHFUFg
Content-Type: application/json

{
  "nombre": "Stefany",
  "apellido": "Luna",
  "cedula": "1548951090",
  "email": "scarlettluna397@gmail.com",
  "password": "Luna.1234",
  "telefono": "099837440",
  "placa_vehiculo": "abc-110",
  "rol": "Estudiante",
  "estado": true
}
